### ISSUE TITLE
City screen is empty if location is not allowed on app start

### ISSUE THREAD

**Issue by oleksii-lubianyi-epam** [OleksiiKolomiiets/WeatherApp#3]
![simulator screen shot - iphone 8 - 2018-05-30 at 11 13 01](https://user-images.githubusercontent.com/28065499/40707892-a4462af2-63fa-11e8-8b7d-dde5c5b8456c.png)
Consider alert user that no data for displaying yet with option to add city

**Comment by OleksiiKolomiiets** [comment]
fixed
